### ISSUE TITLE
默认的指定本地m3u文件不合理，无法指定在线文件

### ISSUE THREAD

**Issue by kilvn** [chinggirltube/M3U-Proxy#4]
现在只能指定本地m3u文件
```
volumes:
      - ./iptv.m3u:/app/iptv.m3u
```

像 https://live.kilvn.com/iptv.m3u 这种在线的是不是只能写个定时任务定时wget到本地了....

能改成支持指定在线url吗

**Comment by chinggirltube** [comment]
你是不是不看文档的说明...
v1.2就已经更新了 
远程导入：
在远程导入框中输入M3U文件的URL
点击"导入"按钮
确认导入后自动更新内容

**Comment by kilvn** [comment]
大概看了下使用说明，没看下面更新说明。我运行看下先

**Comment by kilvn** [comment]
导入失败，500了

![image](https://github.com/user-attachments/assets/cfc21e35-0d21-4abb-bc54-608d5930f635)

**Comment by kilvn** [comment]
![image](https://github.com/user-attachments/assets/458777c4-8b16-49c8-bc1b-b6a3fd3ec16a)
